### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yoyo930021** [COSCUP/2022#1]
- [ ] COSCUP 今年年份成一個變數
- [ ] 抽取開始與結束時間成一個變數
- [ ] 歷年官網網址成一個 computed
- [ ] 使用 `@intlify/vite-plugin-vue-i18n` 套件預先編譯翻譯函數 來減少網頁載入大小
- [ ] 更新使用框架或依賴
- [ ] 議程表最佳化
  - [ ] 抓取議程的穩定性
  - [ ] 儲存喜愛議程
  - [ ] 分享喜愛議程
  - [ ] 篩選議程
  - [ ] 生出每個議程的 og 宣傳圖
  - [ ] 改善議程表靜態頁面的生成方式
  - [ ] 取代原有的 template replace 方式
         Teleport
         獨立頁面
- [ ] 改善 sitemap 的生成
- [ ] 多埋 google analytics 的點
- [ ] 抽出更多變數 讓未來使用更方便
